apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-volume
  namespace: metricsdb
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  gcePersistentDisk:
    pdName: pg-disk
    fsType: ext4
