apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclaim
  namespace: metricsdb
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  storageClassName: slow
  
