apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pg-disk-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: linode-block-storage